# Generated by Django 6.0.3 on 2026-06-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kbchunk",
            name="embedding",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
