# Generated by Django 6.0.3 on 2026-03-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_created_at_project_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("quoted", "Offerte"),
                    ("accepted", "Geaccepteerd"),
                    ("done", "Afgerond"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
