# Generated by Django 6.0.3 on 2026-03-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Concept"),
                    ("quoted", "Offerte"),
                    ("denied", "Afgewezen"),
                    ("accepted", "Geaccepteerd"),
                    ("done", "Afgerond"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
