# Generated by Django 6.0.3 on 2026-05-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_created_at_organization_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
