# Generated by Django 6.0.3 on 2026-05-19 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0003_component_parent"),
        ("configurations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="configuration_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="components.configurationtype",
            ),
        ),
    ]
