# Generated by Django 6.0.3 on 2026-04-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="group_key",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="component",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("boolean", "Boolean"),
                    ("quantity", "Quantity"),
                    ("select", "Select"),
                    ("formula", "Formula"),
                ],
                default="boolean",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="unit",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
