# Generated by Django 6.0.3 on 2026-04-15 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0002_component_group_key_component_input_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="components.component",
            ),
        ),
    ]
