# Generated by Django 6.0.3 on 2026-05-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_component_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationtype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
