# Generated by Django 6.0.3 on 2026-03-31 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentVisualization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "object_key",
                    models.SlugField(
                        help_text="Stable key used by the frontend, e.g. main-hall, left-door."
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[("primitive", "Primitive"), ("model", "3D Model")],
                        default="primitive",
                        max_length=20,
                    ),
                ),
                (
                    "primitive_shape",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("box", "Box"),
                            ("plane", "Plane"),
                            ("sphere", "Sphere"),
                            ("cylinder", "Cylinder"),
                            ("capsule", "Capsule"),
                        ],
                        help_text="Used when object_type = primitive.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "model_key",
                    models.CharField(
                        blank=True,
                        help_text="Used later for real 3D assets, e.g. dome_basic_v1.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "pos_x",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pos_y",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pos_z",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "rot_x",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "rot_y",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "rot_z",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "scale_x",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "scale_y",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "scale_z",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Hex color, e.g. #CCCCCC",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualizations",
                        to="components.component",
                    ),
                ),
                (
                    "configuration_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty if this visualization applies to all configuration types.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualizations",
                        to="components.configurationtype",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("component", "configuration_type", "object_key")},
            },
        ),
    ]
