# Generated by Django 6.0.3 on 2026-03-31 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visualization", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="componentvisualization",
            old_name="scale_x",
            new_name="depth",
        ),
        migrations.RenameField(
            model_name="componentvisualization",
            old_name="scale_y",
            new_name="height",
        ),
        migrations.RenameField(
            model_name="componentvisualization",
            old_name="scale_z",
            new_name="width",
        ),
    ]
